#!/bin/sh

AIRGAP_REGISTRY__DEFAULT_VALUE=""
AIRFLOW_OPERATOR_NAMESPACE__DEFAULT_VALUE="airflowop-system"
AIRFLOW_OPERATOR_IMAGE_TAG__DEFAULT_VALUE="ecp-5.3.0-rc3"
AIRFLOW_BASE_NAMESPACE__DEFAULT_VALUE="airflow-base"
AIRFLOW_BASE_IS_POSTGRES__DEFAULT_VALUE="true"

if [ ! -z "$AIRGAP_REGISTRY" ] && ! expr "$AIRGAP_REGISTRY" : '^.*\/$' 1>/dev/null ; then
    AIRGAP_REGISTRY=${AIRGAP_REGISTRY}"/"
fi

AIRGAP_REGISTRY="${AIRGAP_REGISTRY:-$AIRGAP_REGISTRY__DEFAULT_VALUE}"
AIRFLOW_OPERATOR_NAMESPACE="${AIRFLOW_OPERATOR_NAMESPACE:-$AIRFLOW_OPERATOR_NAMESPACE__DEFAULT_VALUE}"
AIRFLOW_OPERATOR_IMAGE_TAG="${AIRFLOW_OPERATOR_IMAGE_TAG:-$AIRFLOW_OPERATOR_IMAGE_TAG__DEFAULT_VALUE}"
AIRFLOW_BASE_NAMESPACE="${AIRFLOW_BASE_NAMESPACE:-$AIRFLOW_BASE_NAMESPACE__DEFAULT_VALUE}"
AIRFLOW_BASE_IS_POSTGRES="${AIRFLOW_BASE_IS_POSTGRES:-$AIRFLOW_BASE_IS_POSTGRES__DEFAULT_VALUE}"

export AIRGAP_REGISTRY AIRFLOW_OPERATOR_NAMESPACE AIRFLOW_OPERATOR_IMAGE_TAG AIRFLOW_BASE_NAMESPACE

SCRIPTPATH=$(dirname ${0})

kubectl apply -k ${SCRIPTPATH}/../airflow-operator

if [ $AIRFLOW_BASE_IS_POSTGRES = "true" ]; then 
    kubectl apply -k ${SCRIPTPATH}/../airflow-base/overlays/postgres
else
    kubectl apply -k ${SCRIPTPATH}/../airflow-base/overlays/mysql
fi
